### PR TITLE
Removed trx_id/TrxID (issue #149)

### PR DESCRIPTION
**Pull request by last-partizan**
Here it is.

I just removed  trx_id/TrxID and code using it.

Checked rm/get commands, working fine.

I cannot run `make test` becouse it was asking for github passwords.

### CODE REVIEW

**Comment by tyru** [comment]
Great! Thanks :)

* Would you change base to `devel` ?
* Would you rebase or merge `devel` ?
  * This should fix failing CI

**Comment by last-partizan** [comment]
Changed base branch to devel

**Comment by tyru** [comment]
Please rebase or merge devel?
I want to check if CI succeeds (in devel, appveyor config problem is fixed #204).

**Comment by last-partizan** [comment]
Looks like it worked!

**Comment by tyru** [comment]
Seems good, thanks :)

**Pull request merged**
