### PR TITLE
Support go modules

### PR DESCRIPTION
**Pull request by hupfdule**
- Provide go.mod and go.sum
- Utilize Travis to build with and without modules

### CODE REVIEW

**Comment by tyru** [comment]
This is what I wanted and what I should do.
Thanks!
After some investigations, I'll look into this.

**Comment by tyru** [comment]
Ah, please specify `devel` branch for the target branch.

**Comment by hupfdule** [comment]
> Ah, please specify `devel` branch for the target branch.

Damn, I always forget that.

**Comment by tyru** [comment]
Yeah I should write it in CONTRIBUTING.md :sweat_smile:
I hope the default branch in pull request can be changed...

**Comment by tyru** [comment]
Sorry for late merge, thanks!

**Pull request merged**
