### PR TITLE
Fixed edge cases for bash completion

### PR DESCRIPTION
**Pull request by AvianY**
Various edge cases have been solved, such as completion for invalid subcommands etc.

### CODE REVIEW

**Comment by tyru** [comment]
hmm, would you please describe more details?
I want the examples of behaviors you fixed.

**Comment by AvianY** [comment]
completion like:
volt migrate asdf <Tab>  (note, asdf is not a subcommand of migrate)
or:
volt profile list <Tab> (list doesn't have a subcommand or argument)
or:
volt profile add asdf <Tab> (note, asdf is not a profile)
or:
volt get -u <Tab> (should autocomplete **any** plugin, because it updates)
volt get -l <tab> **OR** volt get -u -l <Tab> (should not autocomplete anything, -l means **all**)

**Comment by tyru** [comment]
> `volt migrate asdf <Tab>` (note, asdf is not a subcommand of migrate)
> or:
> `volt profile list <Tab>` (list doesn't have a subcommand or argument)
> or:
> `volt profile add asdf <Tab>` (note, asdf is not a profile)
> or:
> `volt get -u <Tab>` (should autocomplete any plugin, because -u updates)

Yes, it seems good :)

> -l means all

It's slightly different.
`-l` means "the repositories of **current profile**".
But I think the fixed behavior is better, because `-l` and arguments cannot be mixed (arguments are ignored. however, I think mixed `-l` and arguments should be error).

---

I found the case that completion does not work:

```
$ volt profile add def<Tab>
```

doesn't complete `default`.
Can you fix this?

**Comment by tyru** [comment]
Okay, confirmed that the patch fixes `volt profile add def<Tab>` and does not break all above behaviors.

> I am not used to working with github yet, so I don't know how to work with forked repos and other things soefficiently

You can commit the change, and `git push` again.
The change appears also in this page.

**Comment by AvianY** [comment]
Thank you, it worked. I also removed the |new| part of the first if, because "new" does not receive an argument.

**Comment by tyru** [comment]
Perfect! Merged it :)

**Pull request merged**
